trigger:
- main

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'
  appName: 'test-azure-functions_pradeep'
  # Agent VM image name
  #vmImageName: 'default'
  pool: default

- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'
    appType: functionAppLinux # default is functionApp
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
    #Uncomment the next lines to deploy to a deployment slot
    #Note that deployment slots is not supported for Linux Dynamic SKU
    #deployToSlotOrASE: true
    #resourceGroupName: '<Resource Group Name>'
    #slotName: '<Slot name>'