# vm creation through terraform
trigger:
- main

pool: 
  vmImage: ubuntu-latest

jobs:
- job: infra-deploy
  pool: windows-latest
  steps:
  - task: TerraformTaskV2@2
    displayname: 'init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: 'https://github.com/pnarsipur1/azurelearning/tree/main/Infrastructrure/terraform/'
      backendServiceArm: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'
      backendAzureRmResourceGroupName: 'pradeepnp'
      backendAzureRmStorageAccountName: 'pradeepstorageacctname'
      backendAzureRmContainerName: 'tstate'
      backendAzureRmKey: 'tts.tfstate'
  - task: TerraformTaskV2@2
    displayname: 'validate'
    inputs:
    provider: 'azurerm'
      command: 'plan'
      workingDirectory: 'https://github.com/pnarsipur1/azurelearning/tree/main/Infrastructrure/terraform/'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'
  - task: TerraformTaskV2@2
    displayname: 'apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: 'https://github.com/pnarsipur1/azurelearning/tree/main/Infrastructrure/terraform/'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'

