# vm destroy through terraform
trigger:
- main

jobs:
- job: infra_destroy
  pool: default
  steps:
  - task: TerraformTaskV2@2
    displayName: 'destroy'
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/scripts'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(acf8be16-4029-4672-bd15-7c4aa64a5a8a)'